version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: finance-tracker-db
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: finance_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_admin -d finance_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: